### ISSUE TITLE
CSS 笔记

### ISSUE THREAD

**Issue by ryu2gaku** [ryu2gaku/MyTutorial#3]
## float 元素对父元素高度影响的问题 

元素浮动之后，脱离了当前正常的文档流，所以无法撑开其父元素。

```html
<div>
  <div style="float: left;">DIV</div>
</div>
```
子 div 元素设为浮动后，父 div 元素的高度仍旧为 0    

**解决办法**

设置父元素的 overflow 不为默认的 visible 

```html
<div style="overflow: hidden;">
  <div style="float: left;">DIV</div>
</div>
``` 
使用 after 伪元素

```html
<div class="clearfix">
  <div style="float: left;">DIV</div>
</div>
```
```css
.clearfix::after {
  content: "";
  clear: both;
  display: table;
}
```
使用空标签 

```html
<div>
  <div style="float: left;">DIV</div>
  <div style="clear: both;"></div>
</div>
```
