### ISSUE TITLE
codes 

### ISSUE THREAD

**Issue by ryu2gaku** [ryu2gaku/MyTutorial#5]
## 圣杯布局 

``` html
  <div class="container">
    <div class="column main">
      My father was a self-taught mandolin player. He was one of the best string instrument players in our town. He could not read music, but if he heard a tune a few times, he could play it. When he was younger, he was a member of a small country music band. They would play at local dances and on a few occasions would play for the local radio station. He often told us how he had auditioned and earned a position in a band that featured Patsy Cline as their lead singer. He told the family that after he was hired he never went back. Dad was a very religious man. He stated that there was a lot of drinking and cursing the day of his audition and he did not want to be around that type of environment.
    </div>
    <div class="column left"></div>
    <div class="column right"></div>
  </div>
```
``` css
  body { min-width: 450px; }
  .container {
    height: 300px;
    padding: 0 80px 0 100px;
  }
  .column {
    height: 300px;
    float: left;
  }
  .left {
    width: 100px;
    background-color: orange;
    margin-left: -100%;
    position: relative;
    left: -100px;
  }
  .right {
    width: 80px;
    background-color: green;
    margin-left: -80px;
    position: relative;
    right: -80px;
  }
  .main {
    width: 100%;
    background-color: yellow;
  }
```

## 双飞翼布局 

``` html
<div class="container">
    <div class="column main">
      <div class="inner">
        My father was a self-taught mandolin player. He was one of the best string instrument players in our town. He could not read music, but if he heard a tune a few times, he could play it. When he was younger, he was a member of a small country music band. They would play at local dances and on a few occasions would play for the local radio station. He often told us how he had auditioned and earned a position in a band that featured Patsy Cline as their lead singer. He told the family that after he was hired he never went back. Dad was a very religious man. He stated that there was a lot of drinking and cursing the day of his audition and he did not want to be around that type of environment.
      </div>
    </div>
    <div class="column left"></div>
    <div class="column right"></div>
  </div>
```
``` css
  body { min-width: 450px; }
  .container {
    height: 300px;
  }
  .column {
    height: 300px;
    float: left;
  }
  .left {
    width: 100px;
    background-color: orange;
    margin-left: -100%;
  }
  .right {
    width: 80px;
    background-color: green;
    margin-left: -80px;
  }
  .main {
    width: 100%;
    background-color: yellow;
  }
  .main .inner {
    padding: 0 80px 0 100px;
  }
```
